### ISSUE TITLE
Failed to parse Net paramter file:yolov3.cfg

### ISSUE THREAD

**Issue by prem11k** [nhatuan84/android-opencv-yolov3#2]
While running this project on Android studio, It couldn't parse the file even after mentioning the absolute path.
Error: failed to parse net parameter file: /yolov3.cfg in function cv::dnn::experimental_dnn_34_v10::Net cv::dnn::experimental_dnn_34_v10::readNetFromDarknet(const cv::string&, const cv::string&)

**Comment by nhatuan84** [comment]
you can copy the content of that file to code. It is just an array.

**Comment by nhatuan84** [comment]
it is here: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg
please check that the android path is correct by printing the content.

**Comment by prem11k** [comment]
Yes, I did copied the content into a file naming it as yolov3.cfg. Still it
didn't work.

**Comment by nhatuan84** [comment]
can you write a simple app that read the content of the file and print on Terminal.

**Comment by joselochelo** [comment]
I have the same problem. I copied the content into a internal storage and did not work. The app crash

**Comment by joselochelo** [comment]
2019-11-03 23:18:16.598 18212-18212/com.dmp.yolov3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dmp.yolov3, PID: 18212
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dmp.yolov3/com.dmp.yolov3.MainActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.4) /build/3_4-contrib_pack-contrib-android/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: /storage/emulated/0/yolov3.cfg in function 'cv::dnn::experimental_dnn_34_v10::Net cv::dnn::experimental_dnn_34_v10::readNetFromDarknet(const cv::String&, const cv::String&)'
    ]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.4) /build/3_4-contrib_pack-contrib-android/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: /storage/emulated/0/yolov3.cfg in function 'cv::dnn::experimental_dnn_34_v10::Net cv::dnn::experimental_dnn_34_v10::readNetFromDarknet(const cv::String&, const cv::String&)'
    ]
        at org.opencv.dnn.Dnn.readNetFromDarknet_0(Native Method)
        at org.opencv.dnn.Dnn.readNetFromDarknet(Dnn.java:321)
        at com.dmp.yolov3.MainActivity.onCreate(MainActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        	... 11 more

**Comment by antoinediev** [comment]
I also faced to this error, I'm not able to access to cfg and weight files. I have the exact same log than @joselochelo . I Tried with  getExternalStorageDirectory and getDataDirectory
